/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin-subscriptions'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin-subscriptions',
  path: '/admin-subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-subscriptions': typeof AdminSubscriptionsRoute
  '/budgets': typeof BudgetsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/predictions': typeof PredictionsRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-subscriptions': typeof AdminSubscriptionsRoute
  '/budgets': typeof BudgetsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/predictions': typeof PredictionsRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-subscriptions': typeof AdminSubscriptionsRoute
  '/budgets': typeof BudgetsRoute
  '/expenses': typeof ExpensesRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/predictions': typeof PredictionsRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-subscriptions'
    | '/budgets'
    | '/expenses'
    | '/income'
    | '/login'
    | '/onboarding'
    | '/predictions'
    | '/premium'
    | '/pricing'
    | '/reports'
    | '/reset-password'
    | '/savings'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-subscriptions'
    | '/budgets'
    | '/expenses'
    | '/income'
    | '/login'
    | '/onboarding'
    | '/predictions'
    | '/premium'
    | '/pricing'
    | '/reports'
    | '/reset-password'
    | '/savings'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/admin-subscriptions'
    | '/budgets'
    | '/expenses'
    | '/income'
    | '/login'
    | '/onboarding'
    | '/predictions'
    | '/premium'
    | '/pricing'
    | '/reports'
    | '/reset-password'
    | '/savings'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  BudgetsRoute: typeof BudgetsRoute
  ExpensesRoute: typeof ExpensesRoute
  IncomeRoute: typeof IncomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PredictionsRoute: typeof PredictionsRoute
  PremiumRoute: typeof PremiumRoute
  PricingRoute: typeof PricingRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-subscriptions': {
      id: '/admin-subscriptions'
      path: '/admin-subscriptions'
      fullPath: '/admin-subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  BudgetsRoute: BudgetsRoute,
  ExpensesRoute: ExpensesRoute,
  IncomeRoute: IncomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PredictionsRoute: PredictionsRoute,
  PremiumRoute: PremiumRoute,
  PricingRoute: PricingRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
